"""
Django settings for socialinfluence project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
STATIC_ROOT = [
    os.path.join(BASE_DIR, 'socialapp/static')
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$x@4f0dv-(flwc6djsm_@)+!i569u61m3ru#anjv4&z*+8id36'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_URL = 'https://127.0.0.1:8000'

FACEBOOK = {
    'APP_ID': '968268530181566',
    'APP_SECRET': '92db2c83b66feebabb60abf2f1ba58d7',
}

INSTAGRAM = {
    'APP_ID' : '2646964111990255',
    'APP_SECRET' : '7c944c46af1357829cfd10f1b34d3848',
    'AUTH_URL' : 'https://api.instagram.com/oauth/authorize',
    'GRAPH_URL': 'https://graph.instagram.com',
}

TWITTER = {
    'CONSUMER_KEY' : 'OHCexBgdLi8fpvaqHSIbc0FTZ',
    'CONSUMER_SECRET' : 'Pne1nNEFtErlJuqDob7Kh36FpYaNUARhY9fWHx6C8AXYgOzOuF',
    'AUTH_URL': 'https://api.twitter.com/oauth/request_token',
    'ACCESS_TOKEN': '31711065-zwdW9dew0deu2CYvYSgHyHBIE2LWiSKfLna0Nsr14',
    'ACCESS_TOKEN_SECRET': '755k25QvIynt6AgOntvrwmamiWNOxEPdAGeEtbSYQU',
}

SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
LOGIN_REDIRECT_URL = '/dashboard'
ACCOUNT_USERNAME_MIN_LENGTH=3
ACCOUNT_EMAIL_SUBJECT_PREFIX=''
ACCOUNT_EMAIL_VERIFICATION="mandatory"

ACCOUNT_FORMS = {
    'login': 'socialapp.account_forms.CustomLoginForm',
    'reset_password': 'socialapp.account_forms.CustomResetPasswordForm',
    'signup': 'socialapp.account_forms.CustomSignupForm',
}

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend"
)

# Email smtp settings
EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = '134bff1f3f89a6'
EMAIL_HOST_PASSWORD = '036622cafccf81'
EMAIL_HOST_PORT = 2525

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django.contrib.postgres',
    'django.forms',
    'sslserver',
    'captcha',
    'meta',
    'django.contrib.sitemaps',
    'socialapp'
]

RECAPTCHA_PUBLIC_KEY = '6LdX1MAUAAAAAO5Uk0DViPwW9zIpQLSJY5I-9aSm'
RECAPTCHA_PRIVATE_KEY = '6LdX1MAUAAAAAIrD5XCvcPn6UkJaP_mcSNqvP-gy'

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

META_SITE_PROTOCOL='https'
META_SITE_DOMAIN='https://readyinfluencer.com'
META_USE_TITLE_TAG=True
META_USE_OG_PROPERTIES=True
META_USE_TWITTER_PROPERTIES=True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'socialinfluence.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, 'socialapp/templates')
ALLAUTH_TEMPLATES = os.path.join(TEMPLATE_DIR, 'allauth/templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, ALLAUTH_TEMPLATES, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'socialapp.app-context.is_influencer',
                'socialapp.app-context.user_profile',
                'socialapp.app-context.user_interests',
                'socialapp.app-context.sites_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialinfluence.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'social2',
        'USER': 'social',
        'PASSWORD': 'mclone',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# Settings for celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 5120000
