# Generated by Django 2.2.6 on 2019-11-01 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20191101_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaengagement',
            name='post_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
