# Generated by Django 2.2.6 on 2019-11-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_auto_20191101_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
