# Generated by Django 2.2.6 on 2019-11-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_auto_20191101_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramInsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('followers', models.BigIntegerField()),
                ('following', models.BigIntegerField()),
                ('num_posts', models.IntegerField()),
                ('engagement_rate', models.FloatField()),
                ('average_comments', models.FloatField()),
                ('average_likes', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
