# Generated by Django 2.2.6 on 2019-11-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_instagraminsight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagraminsight',
            name='num_posts',
        ),
        migrations.AddField(
            model_name='instagraminsight',
            name='pic',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
