# Generated by Django 2.2.6 on 2019-11-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_auto_20191103_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagraminsight',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
