# Generated by Django 2.2.6 on 2019-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_auto_20191103_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagraminsight',
            name='fullname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
