# Generated by Django 2.2.6 on 2019-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_instagraminsight_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagraminsight',
            name='bio',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
